### ISSUE TITLE
Adapt code and doc for plotly.js 1.52

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2044]
From https://github.com/plotly/plotly.js/releases/tag/v1.52.0

Code
- [x] adapt px code for legend titles #2051
- [x] adapt px code for choropleth geojson
- [x] adapt px code for choropleth+mapbox featureidkey
- [x] add discrete color mode to px choropleth
- [ ] ~~adapt px code for choropleth fitbounds~~
- [ ] ~~decide what values of uniformtext go into the templates~~  postponed
- [ ] ~~px box quartile methods arg?~~ postponed

Doc
- [x] legend titles in legend tutorial #2048
- [x] quartile-computing algorithm  and "pre-computed" q1/median/q3 input signature for `Box` traces @jdamiba 
- [x] geojson geometries in `choropleth` and `scattergeo` traces
- [x] `geo.visible` shortcut attribute
- [x] uniformtext example in tutorials on concerned traces (+ more on a different, more central page??)

Emma:
- [x] showlegend in various places 
- [x] `insidetextorientation` for pie and sunburst #2050
- [x] `intensitymode` to allow cell intensity values in `mesh3d` traces #2052 
- [ ] expand isosurface/streamtube/volume tutorials
- [ ] ~~notifyOnLogging mode in config AND in troubleshooting~~

**Comment by nicolaskruchten** [comment]
@archmoj we could... in which Python doc pages do you think these could go?

**Comment by archmoj** [comment]
https://plot.ly/python/sunburst-charts/
https://plot.ly/python/treemaps/
E.g. mentioning `plotly_sunburstclick` and `plotly_treemapclick` events is important.

**Comment by nicolaskruchten** [comment]
Unfortunately there's no way to show this in static Python docs... this would have to be done in currently-non-existent Dash docs that show dynamic Plotly behaviour...

**Comment by nicolaskruchten** [comment]
OK, this one is "done enough" for the release announcement, we can always add more later :)
